### ISSUE TITLE
Feature enhancement: Parallized jobscript 

### ISSUE THREAD

**Issue by kimrojas** [hhlim12/STATE-BATCH#12]
Improve the current implementation of the jobscript from a simple serial to parallel. 
This can be done using job arrays. 
The advantage of job arrays is that everything is this grouped togethers and a 2nd layer of numbering separates the run.

**Comment by hhlim12** [comment]
@kimrojas , just in case the job arrays is complicated, I suggest the following method.
I put '&' in the execution command and add 'wait' to separate batch calculations.
For example, 
```
# Run system with idx 0017
pushd /sqfs2/cmc/1/work/K22A12/u6b589/STATE-BATCH_2/STATE-BATCH/runs/single_atom/ggapbe/atom_run_0017
mpirun -np 4 ./STATE < V.in > V.out  &
popd

# Run system with idx 0018
pushd /sqfs2/cmc/1/work/K22A12/u6b589/STATE-BATCH_2/STATE-BATCH/runs/single_atom/ggapbe/atom_run_0018
mpirun -np 4 ./STATE < Cr.in > Cr.out  &
popd

wait

# Run system with idx 0019
pushd /sqfs2/cmc/1/work/K22A12/u6b589/STATE-BATCH_2/STATE-BATCH/runs/single_atom/ggapbe/atom_run_0019
mpirun -np 4 ./STATE < Mn.in > Mn.out  &
popd

# Run system with idx 0020
pushd /sqfs2/cmc/1/work/K22A12/u6b589/STATE-BATCH_2/STATE-BATCH/runs/single_atom/ggapbe/atom_run_0020
mpirun -np 4 ./STATE < Fe.in > Fe.out  &
popd

wait
```
It will run job 0017 and 0018 in parallel, wait until they're finished, and run 0019 and 0020 in parallel. 
The disadvantage is we have to wait every calculation to be finished to proceed to the next batch.
Thus we should not group 'fast calculation' and 'slow calculation'. 
I still don't understand the job array that you're trying to do. It seems it is more reliable.
I look forward to it.

**Comment by kimrojas** [comment]
@hhlim12 Thank you for the suggestion. 
I understand this solution but I think the job array approach is easier (and more organized). 
I'll finish it up and ask for the review (with pull request) tomorrow. 
I'm more or less finished with the code, just need to update the QEbatch and explain how to use the new make_jobscript.

**Comment by kimrojas** [comment]
@hhlim12 
I'm done with the jobscript. Do you mind checking it ?
Thank you.

**Comment by hhlim12** [comment]
Hi @kimrojas , thanks a lot. I will check it

**Comment by hhlim12** [comment]
Hi, just update from the previous discussion. I found useful link for the job array (https://centers.hpc.mil/users/advancedTopics/Job_Arrays.html#:~:text=PBS%20Job%20Arrays%20allow%20a,by%20one%20or%20two%20parameters.). In SQUID and ISSP system C, it should be ${PBS_ARRAY_INDEX} instead of {$SGE_TASK_ID}

**Comment by hhlim12** [comment]
Hi @kimrojas , sorry for the late reply.
I'd like to discuss first about how the user provide such information. 
Maybe provide in the `comp_spec` keyword or directly specify in the `qsub_header` file..
I think for simplicity in our code, we should use single variable (e.g., `$SGE_TASK_ID`) and ask the user to redirect the `$PBS_ARRAY_INDEX` to `$SGE_TASK_ID`. Simply by

```
SGE_TASK_ID=$PBS_ARRAY_INDEX
```

Let's have discussion next week if you have time..

**Comment by kimrojas** [comment]
@hhlim12  Sure let's meet. I am available Tuesday after lunch.
Unfortunately, I don't think we can provide it in comp_spec because the TASK_ID is a dynamic variable that's being run by the manager itself _before_ runtime.
