### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by kimrojas** [hhlim12/STATE-BATCH#2]
in Batch code
`pseudolink.unlink(missing_ok=True)`
This `missing_ok` parameter was added from python 3.8 and later. Meaning the python requirement of using batch code is 3.8. 

in state-interface,
I get the error `ERROR: Package 'state-interface' requires a different Python: 3.8.13 not in '<3.7,>=3.6.2'`  when using `pip install .`
This error comes from the limitation that we created for developers in `pyproject.toml` 
line 8: `python = ">=3.6.2,<3.7"`

A short fix I made is replacing it with `python = ">=3.6.2"`.
Maybe we should make a release version of state-interface ?

**Comment by hhlim12** [comment]
Let me working on that. I plan to update the ASE-STATE interface soon.

**Comment by kimrojas** [comment]
@hhlim12 To solve this issue, and also the issue about being private, we can just make a zip of state-interface (install ready version).  We can add this zip file in a pre-release of this repository.

**Comment by hhlim12** [comment]
@kimrojas , OK, I'll add the zip file tomorrow.

**Comment by kimrojas** [comment]
@hhlim12  Solved by dependency-only release
https://github.com/hhlim12/STATE-BATCH/releases/tag/dependency

ase-state-interface many available
