### ISSUE TITLE
Feature enhancement: Uniform naming convention

### ISSUE THREAD

**Issue by kimrojas** [hhlim12/STATE-BATCH#27]
Naming convention should be made uniform for clarity and ease of scripting.

**Comment by tbctan** [comment]
Accomplished with help from Kurt by changing STATEbatch.py and QEbatch.py. This now accepts an input prefix specified in the input.yaml file under the fileprefix heading, if not, the default file prefixes are pw and staterun as specified in the QEbatch/STATEbatch files. 

@ Harry, Please disregard the many push requests I made while mistakenly working in the main branch.
