### ISSUE TITLE
Bug: CSV whitespace in header

### ISSUE THREAD

**Issue by kimrojas** [hhlim12/STATE-BATCH#44]
Species,PSEUDOS,XCTYPE, GMAX

read as ' GMAX'

**Comment by hhlim12** [comment]
I found useful blog for dealing with this issue.

https://towardsdatascience.com/dealing-with-extra-white-spaces-while-reading-csv-in-pandas-67b0c2b71e6a#0f5a

I can implement this once we merged my modification in order to avoid conflict.
