### ISSUE TITLE
Implement mpirun in serial job script

### ISSUE THREAD

**Issue by tbctan** [hhlim12/STATE-BATCH#49]
MPI is implemented in the parallel jobscript by submitting a job with the option --run_idx as in: `python3 {pyfile} --run_idx $ARRAY_TASK_ID` so we get 1 node per task in the array. 

However, the jobscript needs mpi for serial as well so we can make use of multiple nodes or cores to run each job in the series.

This also needs branch #40 -streamlining-serial-job-script to be pushed to main as a prerequisite for continued implementation of mpi in the serial python file.

**Comment by kimrojas** [comment]
Solved in recode in status logger.
