### ISSUE TITLE
Feature request: jobscript maker module

### ISSUE THREAD

**Issue by kimrojas** [hhlim12/STATE-BATCH#5]
Module for creating jobscripts.
Requirements:
1. Should take in input/output filenames from batch class object
2. Take in comp_spec configuration from yaml OR batch class object
3. object-oriented function for easy interfacing

**Comment by hhlim12** [comment]
Hi, I made pull request to address this issue. Can you check it? 

https://github.com/hhlim12/STATE-BATCH/pull/7#issue-1388837224

**Comment by hhlim12** [comment]
Currently it only works in serial. I'm still struggle to run several jobs at once in one node.
