### ISSUE TITLE
Comments for build.py module

### ISSUE THREAD

**Issue by hhlim12** [hhlim12/STATE-BATCH#54]
Hi @uedar , sorry for the late reply.
I have some comments regarding the build.py module.

1. Can you also specify the pbc condition for the unit cell? Plane Wave calculations always use PBC for all directions. So something like `atoms.set_pbc((True, True, True))`
2. Why do bulk and surface have different condition for invalid lattice constant? Has it been discussed before?

Surface & adsorption
``` Python
if len(lattice_constants) > 2:
                raise ValueError("Invalid value for lattice constant")
```

Bulk
``` Python
if len(lattice_constants) > 3:
               raise ValueError("Invalid value for lattice constant")
```

**Comment by uedar** [comment]
Thank you for comments.

>1. Can you also specify the pbc condition for the unit cell? Plane Wave calculations always use PBC for all directions. So something like atoms.set_pbc((True, True, True))

This implementation may be straightforward and possible. But does the pbc property of ASE affect the input file for the DFT calculation?

>2. Why do bulk and surface have different condition for invalid lattice constant? Has it been discussed before?

This is because the maximum number of arguments differs between bulk(a,b,c) and surface(a,c).

```
def bulk(name, crystalstructure=None, a=None, b=None, c=None, *, alpha=None,
         covera=None, u=None, orthorhombic=False, cubic=False,
         basis=None):
```

```
def _surface(symbol, structure, face, size, a, c, vacuum, periodic,
             orthogonal=True):
```

**Comment by hhlim12** [comment]
1. I think it will not affect anything in the STATE calculation since STATE does not take PBC condition as an input.  However, the PBC condition will appear in the archive file. When people do post processing of the archive file (e.g., counting neighbors, calculate density, find environment, etc), they might get wrong results if we specify False PBC).

2. I see. Yes, you're right. Thanks for clarifying.

**Comment by uedar** [comment]
Thank you. I have created a new issue and will implement it.
