### ISSUE TITLE
Archiver on QE: Polish and test

### ISSUE THREAD

**Issue by kimrojas** [hhlim12/STATE-BATCH#59]
The QE implementation of archiver has been done but it is not tested. 
Testing may be a little difficult right now due to #52 (undecided how to run pw.x)

Need to do: 
1. Test if archiver works on QE
2. Fix bugs if not

**Comment by uedar** [comment]
With this PR https://github.com/hhlim12/STATE-BATCH/pull/63, we were able to fix bugs and test archiver on QE.
